frontend:
  - changed-files:
      - any-glob-to-any-file:
          - "public/**"
          - "src/app/presentation/views/**"
          - "scripts/build.ts"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "src/app/domain/**"
          - "src/app/application/**"
          - "src/app/infrastructure/**"
          - "src/app/presentation/routes/**"

database:
  - changed-files:
      - any-glob-to-any-file:
          - "src/app/infrastructure/db/**"
          - "scripts/migration/**"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/labeler.yml"
          - "renovate.json"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"
