services:
  caddy:
    image: caddy:2.11.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    environment:
      DOMAIN: ${DOMAIN}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASS_HASH: ${AUTH_PASS_HASH}
    restart: unless-stopped

  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:${ENVIRONMENT}
    env_file: .env
    restart: unless-stopped

volumes:
  caddy-data:
